update
Y4DRLPJ/XLRON pull request #7
Opened 2024-11-19 17:36 UTC by GENEcccc

2024-11-19 20:32 UTC, myianwang commented
Please add commit message next time

2024-11-19 20:48 UTC, myianwang requested changes
Please add docstring to explain your function

2024-11-20 01:47 UTC, GENEcccc commented
From lines 578 to 586:
define a new class inherits from RSAEnv.

From lines 588 to 591:
check If parameters  are given from RSAEnv, if not，you can set parameters in {} for instance or leave it empty（use parameter of RSAEnv）.

From lines 593 to 608:
initiate parameters for states of environment and assign them to the instance


From lines 665to 669：
define parameters in dictionary {}，or do not need parameters


From lines 792 to 796:
create new instance that only contains multiband parameters instead of single band parameters（RSAEnv）

2024-11-22 09:06 UTC, myianwang approved these changes

2024-11-22 09:07 UTC, merged